# models_2d.py
# =========================================================================
# CHUNK 2: Baseline ResNet-18 for 2D RF Spectrograms
# Modified ResNet-18 architecture optimized for small (64x5) spectrograms
# generated by Person 3's Kaiser-windowed STFT converter.
# No torchvision dependency — built from scratch for full control.
# =========================================================================

import torch
import torch.nn as nn
import torch.nn.functional as F


# ──────────────────────────────────────────────────────────────
# Building Block
# ──────────────────────────────────────────────────────────────

class BasicBlock(nn.Module):
    """Standard ResNet BasicBlock: two 3x3 conv layers + skip connection."""
    expansion = 1

    def __init__(self, in_planes, planes, stride=1):
        super().__init__()
        self.conv1 = nn.Conv2d(
            in_planes, planes, kernel_size=3, stride=stride, padding=1, bias=False
        )
        self.bn1 = nn.BatchNorm2d(planes)
        self.conv2 = nn.Conv2d(
            planes, planes, kernel_size=3, stride=1, padding=1, bias=False
        )
        self.bn2 = nn.BatchNorm2d(planes)

        # Shortcut: identity when dims match, learned 1x1 projection otherwise
        self.shortcut = nn.Sequential()
        if stride != 1 or in_planes != planes * self.expansion:
            self.shortcut = nn.Sequential(
                nn.Conv2d(
                    in_planes, planes * self.expansion,
                    kernel_size=1, stride=stride, bias=False
                ),
                nn.BatchNorm2d(planes * self.expansion),
            )

    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        out += self.shortcut(x)
        out = F.relu(out)
        return out


# ──────────────────────────────────────────────────────────────
# ResNet-18 for 2D Spectrograms
# ──────────────────────────────────────────────────────────────

class ResNet18_2D(nn.Module):
    """
    Modified ResNet-18 for small 2D RF spectrograms.

    Adaptations from standard ImageNet ResNet-18:
      1. conv1: 3x3 kernel (not 7x7), stride=1 — preserves spatial
         resolution on small (64×5) spectrograms.
      2. No initial MaxPool — prevents excessive downsampling.
      3. Configurable input channels: 1 (grayscale) or 3 (hybrid).
      4. Dynamic final FC layer sized to num_classes.

    Expected input shape:  [B, in_channels, 64, 5]
    Output shape:          [B, num_classes]

    Args:
        num_classes (int): Number of modulation classes. Default 11 (RadioML 2016.10a).
        in_channels (int): Number of input channels. 1 for grayscale, 3 for hybrid.
    """

    def __init__(self, num_classes=11, in_channels=1):
        super().__init__()
        self.in_planes = 64

        # ── Stem (no MaxPool) ──────────────────────────────────
        self.conv1 = nn.Conv2d(
            in_channels, 64, kernel_size=3, stride=1, padding=1, bias=False
        )
        self.bn1 = nn.BatchNorm2d(64)

        # ── Residual Layers [2, 2, 2, 2] ──────────────────────
        self.layer1 = self._make_layer(64,  num_blocks=2, stride=1)
        self.layer2 = self._make_layer(128, num_blocks=2, stride=2)
        self.layer3 = self._make_layer(256, num_blocks=2, stride=2)
        self.layer4 = self._make_layer(512, num_blocks=2, stride=2)

        # ── Classification Head ────────────────────────────────
        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc = nn.Linear(512 * BasicBlock.expansion, num_classes)

        # ── Weight Initialization (Kaiming) ────────────────────
        self._init_weights()

    def _make_layer(self, planes, num_blocks, stride):
        """Build a residual layer with `num_blocks` BasicBlocks."""
        strides = [stride] + [1] * (num_blocks - 1)
        layers = []
        for s in strides:
            layers.append(BasicBlock(self.in_planes, planes, s))
            self.in_planes = planes * BasicBlock.expansion
        return nn.Sequential(*layers)

    def _init_weights(self):
        """Kaiming initialization for stable gradient flow."""
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode="fan_out", nonlinearity="relu")
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.Linear):
                nn.init.normal_(m.weight, 0, 0.01)
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        """
        Forward pass through the modified ResNet-18.

        Feature map sizes for input [B, 1, 64, 5]:
            conv1  → [B, 64,  64, 5]
            layer1 → [B, 64,  64, 5]
            layer2 → [B, 128, 32, 3]
            layer3 → [B, 256, 16, 2]
            layer4 → [B, 512,  8, 1]
            avgpool→ [B, 512,  1, 1]
            fc     → [B, num_classes]
        """
        # Stem
        x = F.relu(self.bn1(self.conv1(x)))

        # Residual blocks
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        # Pool → Flatten → Classify
        x = self.avgpool(x)
        x = torch.flatten(x, 1)
        x = self.fc(x)

        return x


# =========================================================================
# Smoke Test
# =========================================================================
if __name__ == "__main__":
    print("=" * 58)
    print("   CHUNK 2: ResNet-18 2D ARCHITECTURE SMOKE TEST")
    print("=" * 58)

    # ── Test 1: Grayscale input [B, 1, 64, 5] ─────────────────
    model_gray = ResNet18_2D(num_classes=11, in_channels=1)
    x_gray = torch.randn(8, 1, 64, 5)
    out_gray = model_gray(x_gray)

    assert out_gray.shape == (8, 11), f"Expected (8, 11), got {out_gray.shape}"
    print(f"[PASS] Grayscale  input {tuple(x_gray.shape)} -> output {tuple(out_gray.shape)}")

    # ── Test 2: Hybrid input [B, 3, 64, 5] ────────────────────
    model_hybrid = ResNet18_2D(num_classes=11, in_channels=3)
    x_hybrid = torch.randn(8, 3, 64, 5)
    out_hybrid = model_hybrid(x_hybrid)

    assert out_hybrid.shape == (8, 11), f"Expected (8, 11), got {out_hybrid.shape}"
    print(f"[PASS] Hybrid     input {tuple(x_hybrid.shape)} -> output {tuple(out_hybrid.shape)}")

    # ── Test 3: Custom class count (MATLAB dataset = 5 classes) ─
    model_custom = ResNet18_2D(num_classes=5, in_channels=1)
    x_custom = torch.randn(4, 1, 64, 5)
    out_custom = model_custom(x_custom)

    assert out_custom.shape == (4, 5), f"Expected (4, 5), got {out_custom.shape}"
    print(f"[PASS] Custom     input {tuple(x_custom.shape)} -> output {tuple(out_custom.shape)} (5 classes)")

    # ── Parameter Count ────────────────────────────────────────
    total_params = sum(p.numel() for p in model_gray.parameters())
    trainable = sum(p.numel() for p in model_gray.parameters() if p.requires_grad)
    print(f"\n[INFO] Total parameters    : {total_params:,}")
    print(f"[INFO] Trainable parameters: {trainable:,}")

    print("\n" + "=" * 58)
    print("   [SUCCESS] ResNet-18 2D architecture verified!")
    print("=" * 58)
