# subsystem2_1d/dataloader_1d.py
# =========================================================
# Subsystem 2 — 1D PyTorch Dataset & DataLoader Factory
# Person 2 | feature/1d-model-p2
#
# Design contract:
#   - Reads ONLY from pre-existing .npy arrays produced by
#     Person 1's dataset_agent.py (never re-generates splits).
#   - Split indices (train_idx.npy / val_idx.npy / test_idx.npy)
#     are treated as immutable, locked artifacts.
#   - Signal shape entering this module: (2, 128)  float32
#   - Label shape:                        scalar    int64
# =========================================================

import os
import sys
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
from typing import Optional, Callable, Tuple

# Allow importing from the repository root (for cross-subsystem imports if needed)
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)


# ---------------------------------------------------------
# Constants
# ---------------------------------------------------------

# Expected signal dimensions — changing these would break the model
_EXPECTED_CHANNELS    = 2    # I and Q
_EXPECTED_TIME_STEPS  = 128  # samples per frame
_SIGNAL_SHAPE         = (_EXPECTED_CHANNELS, _EXPECTED_TIME_STEPS)

# Locked split file names (generated by Person 1's dataset_agent.py)
_SPLIT_FILES = {
    "train": "train_idx.npy",
    "val":   "val_idx.npy",
    "test":  "test_idx.npy",
}

# Full-dataset arrays generated by Person 1
_DATA_FILES = {
    "X":    "X_all.npy",    # (220000, 2, 128) float32 — pre-normalized
    "y":    "y_all.npy",    # (220000,)        int64
    "snrs": "snrs_all.npy", # (220000,)        int32
}


# ---------------------------------------------------------
# 1. PyTorch Dataset
# ---------------------------------------------------------

class RFSignalDataset1D(Dataset):
    """
    Lightweight PyTorch Dataset for 1D IQ signal classification.

    Wraps a pre-loaded NumPy array slice (already indexed via locked split
    indices) to avoid holding redundant copies of the full 220k dataset.

    Args:
        X         (np.ndarray):          Signal array, shape (N, 2, 128) float32.
        y         (np.ndarray):          Integer class labels, shape (N,) int64.
        transform (Callable, optional):  A callable applied to each signal
                                         PyTorch tensor *after* conversion.
                                         Intended for IQAugmentation or
                                         custom per-sample transforms.

    Returns per __getitem__:
        signal (torch.Tensor): Shape (2, 128), dtype float32.
        label  (torch.Tensor): Scalar, dtype int64.
    """

    def __init__(
        self,
        X: np.ndarray,
        y: np.ndarray,
        transform: Optional[Callable] = None,
    ):
        if X.ndim != 3 or X.shape[1:] != _SIGNAL_SHAPE:
            raise ValueError(
                f"RFSignalDataset1D expects X of shape (N, 2, 128), "
                f"received {X.shape}."
            )
        if len(X) != len(y):
            raise ValueError(
                f"Length mismatch: X has {len(X)} samples, y has {len(y)}."
            )

        # Store as contiguous float32 / int64 — avoids dtype mismatches in DataLoader
        self.X         = np.ascontiguousarray(X, dtype=np.float32)
        self.y         = np.ascontiguousarray(y, dtype=np.int64)
        self.transform = transform

        self._num_classes = int(np.max(y)) + 1

    # ----------------------------------------------------------

    def __len__(self) -> int:
        return len(self.X)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor]:
        signal = torch.from_numpy(self.X[idx])   # (2, 128) float32
        label  = torch.tensor(self.y[idx], dtype=torch.int64)

        if self.transform is not None:
            signal = self.transform(signal)

        return signal, label

    # ----------------------------------------------------------

    @property
    def num_classes(self) -> int:
        """Total number of unique modulation classes in this split."""
        return self._num_classes

    def __repr__(self) -> str:
        return (
            f"RFSignalDataset1D("
            f"n_samples={len(self)}, "
            f"signal_shape={_SIGNAL_SHAPE}, "
            f"num_classes={self._num_classes}, "
            f"transform={self.transform})"
        )


# ---------------------------------------------------------
# 2. Internal Helper — safely load a .npy file
# ---------------------------------------------------------

def _load_npy(data_dir: str, filename: str) -> np.ndarray:
    """Load a NumPy .npy file with a descriptive error message on failure."""
    path = os.path.join(data_dir, filename)
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"\n[Subsystem2] Could not find '{filename}' in '{data_dir}'.\n"
            f"  → Make sure you have run 'python dataset_agent.py' from the repo root\n"
            f"    to generate the processed .npy arrays before using this DataLoader."
        )
    return np.load(path)


# ---------------------------------------------------------
# 3. DataLoader Factory
# ---------------------------------------------------------

def get_1d_dataloaders(
    data_dir:    str  = "./data",
    batch_size:  int  = 64,
    num_workers: int  = 2,
    augment_train: bool = False,
    train_transform: Optional[Callable] = None,
    val_test_transform: Optional[Callable] = None,
    pin_memory: Optional[bool] = None,
    seed: int = 42,
) -> Tuple[DataLoader, DataLoader, DataLoader]:
    """
    Build and return the three locked PyTorch DataLoaders for Subsystem 2.

    Reads Person 1's immutable split indices and pre-normalized signal arrays
    from `data_dir`. The three splits (train / val / test) are guaranteed to
    be non-overlapping and reproducible across all team members.

    Args:
        data_dir     (str):  Absolute or relative path to the data directory
                             containing X_all.npy, y_all.npy, and *_idx.npy files.
                             Defaults to "./data" (relative to repo root).
        batch_size   (int):  Number of samples per batch. Default: 64.
        num_workers  (int):  Subprocesses for data loading (DataLoader).
                             Set to 0 to disable multiprocessing (safer on Windows).
                             Default: 2.
        augment_train (bool): If True AND no explicit train_transform is given,
                              wraps the training split with IQAugmentation(enabled=True).
                              Val/test loaders are never augmented.
        train_transform (Callable, optional):
                              Explicit transform for the training split.
                              Overrides `augment_train` if supplied.
        val_test_transform (Callable, optional):
                              Transform for val and test splits (e.g., inference-time
                              normalization). Usually None since data is pre-normalized.
        pin_memory   (bool, optional):
                              Pin tensors to CUDA page-locked memory. Auto-detected
                              from torch.cuda.is_available() if None.
        seed         (int):  Random seed for DataLoader worker initialization,
                             ensuring reproducible batch ordering.

    Returns:
        Tuple[DataLoader, DataLoader, DataLoader]:
            (train_loader, val_loader, test_loader)

    Raises:
        FileNotFoundError: If any required .npy file is missing from data_dir.

    Example:
        >>> train_loader, val_loader, test_loader = get_1d_dataloaders(
        ...     data_dir="./data", batch_size=64
        ... )
        >>> for signals, labels in train_loader:
        ...     assert signals.shape == (64, 2, 128)
        ...     assert labels.shape  == (64,)
        ...     break
    """

    # ----------------------------------------------------------
    # 3.1  Resolve data_dir — try multiple candidate paths
    # ----------------------------------------------------------
    if not os.path.isabs(data_dir):
        candidates = [
            data_dir,
            os.path.join(_REPO_ROOT, "data"),
            os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "data"),
        ]
        for candidate in candidates:
            if os.path.isdir(candidate):
                data_dir = os.path.abspath(candidate)
                break

    # ----------------------------------------------------------
    # 3.2  Load full dataset arrays (pre-normalized by Person 1)
    # ----------------------------------------------------------
    print(f"[Subsystem2] Loading dataset from: {data_dir}")

    X_all    = _load_npy(data_dir, _DATA_FILES["X"])     # (220000, 2, 128)
    y_all    = _load_npy(data_dir, _DATA_FILES["y"])     # (220000,)

    print(f"  ✓ X_all loaded  — shape: {X_all.shape}, dtype: {X_all.dtype}")
    print(f"  ✓ y_all loaded  — shape: {y_all.shape}, dtype: {y_all.dtype}")

    # ----------------------------------------------------------
    # 3.3  Load locked split indices
    # ----------------------------------------------------------
    train_idx = _load_npy(data_dir, _SPLIT_FILES["train"])
    val_idx   = _load_npy(data_dir, _SPLIT_FILES["val"])
    test_idx  = _load_npy(data_dir, _SPLIT_FILES["test"])

    print(f"  ✓ train_idx — {len(train_idx):>7,} samples  (≈70%)")
    print(f"  ✓ val_idx   — {len(val_idx):>7,} samples  (≈20%)")
    print(f"  ✓ test_idx  — {len(test_idx):>7,} samples  (≈10%)")

    # ----------------------------------------------------------
    # 3.4  Slice arrays using locked indices
    # ----------------------------------------------------------
    X_train, y_train = X_all[train_idx], y_all[train_idx]
    X_val,   y_val   = X_all[val_idx],   y_all[val_idx]
    X_test,  y_test  = X_all[test_idx],  y_all[test_idx]

    # ----------------------------------------------------------
    # 3.5  Resolve transforms
    # ----------------------------------------------------------
    # Training transform: explicit override > augment_train flag > None
    if train_transform is None and augment_train:
        from subsystem2_1d.normalization_1d import IQAugmentation
        train_transform = IQAugmentation(enabled=True)

    # ----------------------------------------------------------
    # 3.6  Build Datasets
    # ----------------------------------------------------------
    train_ds = RFSignalDataset1D(X_train, y_train, transform=train_transform)
    val_ds   = RFSignalDataset1D(X_val,   y_val,   transform=val_test_transform)
    test_ds  = RFSignalDataset1D(X_test,  y_test,  transform=val_test_transform)

    # ----------------------------------------------------------
    # 3.7  Resolve pin_memory
    # ----------------------------------------------------------
    if pin_memory is None:
        pin_memory = torch.cuda.is_available()

    # ----------------------------------------------------------
    # 3.8  Worker seed function for reproducibility
    # ----------------------------------------------------------
    def _worker_init_fn(worker_id: int):
        np.random.seed(seed + worker_id)
        torch.manual_seed(seed + worker_id)

    # ----------------------------------------------------------
    # 3.9  Build DataLoaders
    # ----------------------------------------------------------
    # Windows multiprocessing requires num_workers=0 by default to avoid
    # "freeze_support" errors; surface a warning if user requests workers.
    effective_workers = num_workers
    if sys.platform == "win32" and num_workers > 0:
        import warnings
        warnings.warn(
            f"[Subsystem2] Windows detected. Forcing num_workers=0 to avoid "
            f"multiprocessing issues. Set num_workers=0 explicitly to silence this.",
            RuntimeWarning,
            stacklevel=2,
        )
        effective_workers = 0

    _loader_kwargs = dict(
        batch_size=batch_size,
        num_workers=effective_workers,
        pin_memory=pin_memory,
        worker_init_fn=_worker_init_fn if effective_workers > 0 else None,
        persistent_workers=effective_workers > 0,
    )

    train_loader = DataLoader(train_ds, shuffle=True,  **_loader_kwargs)
    val_loader   = DataLoader(val_ds,   shuffle=False, **_loader_kwargs)
    test_loader  = DataLoader(test_ds,  shuffle=False, **_loader_kwargs)

    print(f"\n[Subsystem2] DataLoaders built successfully.")
    print(f"  Batch size     : {batch_size}")
    print(f"  pin_memory     : {pin_memory}")
    print(f"  num_workers    : {effective_workers}")
    print(f"  Train batches  : {len(train_loader)}")
    print(f"  Val   batches  : {len(val_loader)}")
    print(f"  Test  batches  : {len(test_loader)}")

    return train_loader, val_loader, test_loader
